[build]
command = "npm install --legacy-peer-deps && npm run prebuild && CI= npm run build"
publish = "build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "22"
DISABLE_ESLINT_PLUGIN = "true"
