[build]
  command = "npm run prebuild && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.3"
[build.environment]
  NODE_VERSION = "18.20.3"
  DISABLE_ESLINT_PLUGIN = "true"
